# Generated by Django 3.2.25 on 2025-12-30 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_stock_stocktxn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('SUBMITTED', '已提交'), ('ISSUED', '已发放'), ('CANCELLED', '已取消')], default='DRAFT', max_length=16)),
                ('machine_no', models.CharField(blank=True, max_length=64, verbose_name='设备号')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='用途/备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='发放时间')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_requisitions', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(verbose_name='数量')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='requisition.requisition')),
            ],
        ),
    ]
