# Generated by Django 3.2.25 on 2025-12-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='编码')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('spec', models.CharField(blank=True, max_length=128, verbose_name='规格/型号')),
                ('unit', models.CharField(default='pcs', max_length=16, verbose_name='单位')),
                ('category', models.CharField(blank=True, max_length=64, verbose_name='分类')),
                ('location', models.CharField(blank=True, max_length=64, verbose_name='库位')),
                ('min_stock', models.PositiveIntegerField(default=0, verbose_name='最低库存')),
                ('is_controlled', models.BooleanField(default=False, verbose_name='受控物料')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
